version: '3.8'

services:
  postgres_auth:
    image: postgres
    container_name: postgres-authuser
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: authuser
      POSTGRES_USER: viana
      POSTGRES_PASSWORD: docker
    ports:
      - "5433:5432"
    networks:
      - learneasy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - learneasy

  microservice-authuser:
    image: joel37/learn-authuser
    restart: always
    build: .
    working_dir: /authservice
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATA.SOURCE.URL: jdbc:postgresql://postgres_auth:5433/authuser
      SPRING.DATA.SOURCE.USERNAME: viana
      SPRING.DATA.SOURCE.PASSWORD: docker
    ports:
      - "8081:8081"
    command: mvn spring-boot:run
    depends_on:
      - postgres_auth
      - microservice-service-registry
      - microservice-api-gateway
      - rabbitmq
    networks:
      - learneasy

networks:
  learneasy:
    driver: bridge
