version: '3.8'

services:
  postgres_auth:
    image: postgres
    container_name: postgres-authuser
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: authuser
      POSTGRES_USER: viana
      POSTGRES_PASSWORD: docker123
    ports:
      - "5433:5432"
    networks:
      - learneasy

  postgres_course:
    image: postgres
    container_name: postgres-course
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: course
      POSTGRES_USER: viana
      POSTGRES_PASSWORD: docker123
    ports:
      - "5434:5432"
    networks:
      - learneasy

  postgres_purchase:
    image: postgres
    container_name: postgres-purchase
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: purchase
      POSTGRES_USER: viana
      POSTGRES_PASSWORD: docker123
    ports:
      - "5435:5432"
    networks:
      - learneasy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - learneasy

networks:
  learneasy:
    driver: bridge
