server:
  port: 8081
  servlet:
    context-path: '/learn-auth/'

spring:
  application:
    name: learn-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 6MB
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

file:
  upload-dir: /home/joelmaciel/1_Projetos/java/LearnEasy/upload

learn:
  auth:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 14400000
  serviceRegistry:
    username: ${NAME}
    password: ${PASSWORD}
  broker:
    exchange: userevent

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${learn.serviceRegistry.username}:${learn.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

logging:
  level:
    com.joel: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
