server:
  port: 8081
  servlet:
    context-path: '/learn-auth/'

spring:
  application:
    name: learn-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authuser
    username: viana
    password: docker123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 6MB
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

file:
  upload-dir: /home/joelmaciel/1_Projetos/java/LearnEasy/upload

learn:
  auth:
    jwtSecret: 7Xt4tQbTnqmE?xDY4j3DphnMPHScU2EoBi9zarOtRTE9DPNJAdGz7X-ge/uZjZtiMcVKf4gyhd34QVBhjnxO0v9/KD7=2LnGNaqQI!5LgCfXz5Q-n1OD7b=96J5960mr
    jwtExpirationMs: 14400000
  serviceRegistry:
    username: serviceregistry
    password: learn123sr
  broker:
    exchange: userevent

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://serviceregistry:learn123sr@localhost:8761/eureka'
  instance:
    hostname: localhost

logging:
  level:
    com.joel: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
