name: Continuos Integration Git Hub Actons

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v3.2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSOWRD }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build application JAR
      working-directory: ./authuser
      run: mvn clean package

    - name: Docker compose Build
      working-directory: ./authuser
      run: mvn clean package 
    - name: Push to Docker Hub Conatiner Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-authuser:latest ${{ secrets.DOCKER_USERNAME }}/learn-authuser:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-authuser:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-authuser:latest
       










    
